Apolo2 entrega3
elagarrigue/AyDS21-AK-Apolo2 pull request #3
Opened 2021-05-18 21:46 UTC by kevschweitzer

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +    fun getInfo(dbHelper: ArtistDataBase, artist: String): String? {
- Mismo problema con el dbHelper como parámetro
- El método tiene mas de una responsabilidad. Por un lado se debería hacer la query y por el otro el procesamiento del cursor

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +        val selectionArgs = arrayOf(artist)
Esta variable no es necesaria. Se puede hacer inline

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +        return if (cursor.moveToFirst()) {
Que haya un cursor.close() en una sentencia de return es poco clean. Obtener el resultado antes en una variable

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/LastFMAPI.kt
> +    fun getArtistInfo(@Query("artist") artist: String?): Call<String>
No se espera que sea null el artist en esta instancia. A lo sumo puede venir un text vacio. Sacar el nullable en este método y en todos los anteriores que lo requieran y usar un String vacio en el caso de error

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +
Borrar linea de más

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +    private var textPane: TextView? = null
Este nombre no es representativo. Poner un nombre que represente la parte de la vista

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +    private fun open(artist: String?) {
Inicializar base de datos y showArtistInfo son responsabilidades distintas para estar en un metodo como open. 
Pueden inicializar la base de datos directamente en la variable global y poner showArtistInfo directamente en el onCreate

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
Esto deberia estar en un metodo aparte

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +    @SuppressWarnings("deprecation")
No es necesario

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            infoArtist = getInfoArtistFromDB(artistName)
Que el algoritmo de repository esté en un método aparte. Esta función de por si tiene 2 responsabilidades, buscar los datos y actualizar la UI

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        val lastFMAPI = createLastFMAPI()
Crean acá la API para pasarla por parámetro. Directamente creenla donde la usan (esto igual va a cambiar cuando separemos en MVC)

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        urlLastFM = url!!.asString
El doble signo les puede generar un crash si url es null. Usen url?.asString

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            artistDataBase?.getInfo(artistDataBase!!, artistName!!)
Eviten el doble signo. Si llega a ser null les crashea la app

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            textPane!!.text = infoArtist?.let { this.fromHtml(it) }
textPane?.text seria correcto

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        val imageUrl = LASTFM_IMAGE_WIKIPEDIA
crear una variable para albergar una constante no es necesario

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        val jobj = gson.fromJson(callResponse.body(), JsonObject::class.java)
jobj?

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        return jobj["artist"].asJsonObject
"artist" puede ser constante

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            artistNameText = extract.asString.replace("\\n", "\n")
Dos asignaciones seguidas a la misma variable no es clean

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        var artistNameText = "No Results"
artistNameText vendría a ser la descripción del artista? Poner otro nombre

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +    private fun saveArtist(artistName: String?, extract: JsonElement?): String {
saveArtist está teniendo 3 responsabilidades. Obtener el texto de extract, guardarlo y retornar el String del resultado. Separar

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        val builder = StringBuilder()
Pueden usar StringBuilder().apply {
    append()
    append()
    append()
    ...
}

2021-05-18 22:53 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        builder.append("<html><div width=400>")
El 400 deberia ser una constante

2021-05-18 22:55 UTC, aribru17 requested changes
Se eliminó el PR anterior y se creó uno nuevo para visualizar únicamente los cambios de este branch.

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +internal const val SORTORDER = "artist DESC"
Cuando se usa más de una palabra para una constante es mejor separar con guión bajo (ya que no se puede camel case).
Quedaria SORT_ORDER y DATABASE_NAME

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +        val projection = arrayOf(
Siendo que la projection es solo para obtener la query deberia estar dentro de getCursor

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +    private fun getInfoFromCursor(cursor: Cursor): String? {
Opcional: GetInfoFromCursor podria ser una extension function

`fun Cursor.getInfoColumn(): String {...} `

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +internal const val WIDTH = 400
Width de que?

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +    private fun urlButtonOnClick() {
Mejor nombre es setUrlButtonListener

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +    private fun showArtistInfo(artistName: String) {
Abstraigan en un método aparte el algoritmo que sería el del repositorio

```
Thread {
    val artistInfo = getArtistInfo(artistName) //Este metodo seria el del repo
    setArtistInfoOnUI(artistInfo)
}
```

Y el metodo del repositorio (que aun no tienen pero para que ya les quede separado)

```
fun getArtistInfo(artistName: String): String {
  var artistInfo = database.getArtistInfo(artistName)
  if(artistInfo != null) {
      markAsAlreadyInDatabase()
  } else {
      artistInfo = api.getArtistInfo()
      database.save(artistInfo)
   }
      
  return artistInfo
}
```

Nota: Es una mezcla de codigo y pseudocodigo eh no es tal cual

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +            artistDataBase.saveArtist(artistName, infoArtist)
Este save es el que tiene que estar en el algoritmo del repositorio. Este metodo solo deberia encargarse de obtener el dato del servicio. No de guardarlo.

Fijense que pueden usar el try catch como expresion

```
return try {
   blablabla
} catch() {
  e.printStackTrace()
  "" // valor por defecto
}

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +
Linea de mas

2021-05-21 00:36 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +
No hace falta agregar estos enters para separar todo. Pueden ademas usar el if como expresion (analogo a lo que les dije del try catch)

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +    private fun getInfoArtistFromLastFM(artistName: String): String {
Varias cosas que comentar sobre este método:

- En primer lugar el nombre seria mejor getInfoArtistFromService y que después el otro método especifique la API correspondiente
- El return que tienen donde asignan extractInfoArtist está raro. Deberían hacer que extractInfoFromResponse retorne directamente un String? (pasando el asString a ese metodo). Si retorna nulo pueden poner el elvis operator con vacio (sacando el return).
 `val extractInfoArtist = extractInfoFromResponse(lastFMResponse) ?: ""`
- Siendo que pasamos el asString al metodo extractInfoFromResponse el getArtistNameDescription la unica responsabilidad que tiene es darle formato, y el formato es responsabilidad de la vista. Ustedes del servicio deben obtener solo el dato y guardarlo en la base de datos plano. Cuando la vista quiera mostrarlo tomará el dato plano y le dará el formato correspondiente
- El espacio entre printStackTrace() y el resultado vacio es innecesario

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +        val url = artist[URL]
No es necesaria la variable url
```suggestion
        urlLastFm = artist[URL]?.asString
```

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +
borrar linea de más

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +
borrar linea de más

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +
borrar linea más

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +        var info:String? = null
Mala separación de simbolos
```suggestion
        var info: String? = null
```

2021-05-24 14:14 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDataBase.kt
> +
linea de más

2021-05-24 14:17 UTC, aribru17 requested changes
presten atención a las líneas que dejan de más en los métodos porque en el afán de separar partes de código están agregando muchas líneas que son innecesarias.

2021-05-25 22:37 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistDescriptionActivity.kt
> +            getArtistNameDescription(artistName, extractInfoArtist)
Hago esta corrección porque ya estaba hecha antes y no lo corrigieron. Les copio lo mismo 

`El getArtistNameDescription la unica responsabilidad que tiene es darle formato, y el formato es responsabilidad de la vista. Ustedes del servicio deben obtener solo el dato y guardarlo en la base de datos plano. Cuando la vista quiera mostrarlo tomará el dato plano y le dará el formato correspondiente`

Esto quiere decir que el getArtistNameDescription tiene que estar fuera del metodo que maneja el servicio. Ustedes deberian llamar a `getInfoArtist` (como lo estan haciendo dentro del thread) y a ese resultado darle formato antes de mostrarlo. De la forma en que lo están haciendo estan guardando en la base de datos el texto ya con el formato html puesto, lo que es incorrecto. Deberian guardar un dato, no el dato con formato

2021-05-25 22:41 UTC, aribru17 requested changes
Quedó sin corregir un comentario hecho el día de ayer.

2021-05-26 11:40 UTC, aribru17 approved these changes

2021-05-26 11:40 UTC, merged